# .github/workflows/ci.yml

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check Docker version
      run: docker version

    - name: Build Docker Image
      # Runs the build and starts services (db and web) in detached mode
      run: docker compose up -d --build

    - name: Wait for DB and Run Migrations
      # Added a short sleep to ensure the database container is ready before migrating
      run: |
        sleep 10
        docker compose exec web python manage.py migrate

    - name: Run Tests
      run: docker compose exec web python manage.py test

    - name: Shut down services
      run: docker compose down